name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up latest Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.X
    - name: Install dependencies
      run: |
        make install 
        make dev-install
    - name: Lint with autopep8
      run: autopep8 --diff --recursive pyprojecttemplate/
